### ISSUE TITLE
Add TokenController method for either instant or ratified mints depending on current pools

### ISSUE THREAD

**Issue by wjmelements** [trusttoken/true-currencies#102]
It would be useful operationally if there was a unified method that requested a mint, but mints instantly if there is enough in that pool.

**Comment by vanruch** [comment]
Looks like we don't need it anymore
@RafaelCosman can you confirm?

**Comment by RafaelCosman** [comment]
Yes let's go ahead and close this issue for now... but we do still have some mint reliability issues and possibly this could increase reliability. I think this is something @hal909 can assess as part of more broadly looking at mint and redemption reliability.
