### ISSUE TITLE
Deprecate Burn V1

### ISSUE THREAD

**Issue by wjmelements** [trusttoken/true-currencies#103]
Because redemption addresses are more-convenient, and nobody uses burn v1 anymore, we want to remove support for it.

**Comment by wjmelements** [comment]
The most-recent burn v1 I could find was https://etherscan.io/tx/0xc39d370356c1bcf13a1eb0828e00a7b2c85a6c9ae5291e2c2d1575ad1af460f1

**Comment by vanruch** [comment]
Done in #253
