### ISSUE TITLE
Support Kovan Testnet

### ISSUE THREAD

**Issue by wjmelements** [trusttoken/true-currencies#108]
This documents work toward supporting the Kovan Testnet.

**Comment by wjmelements** [comment]
I have finished work for the deposit address registrar, the registry, and 2 of the tokens (TUSD, TCAD). Will do the others later.

**Comment by wjmelements** [comment]
If anyone wants any of these in particular, I can prioritize them upon request.

**Comment by vanruch** [comment]
We've decided to use Ropsten as a testnet instead
