### ISSUE TITLE
TrueCoinReceiver + Autosweep: originalSender?

### ISSUE THREAD

**Issue by wjmelements** [trusttoken/true-currencies#121]
In the case of autosweep, we use the intermediate alias address as the original sender parameter, which preserves some information about the intent of the transfer. But for some contracts, they may be more interested in the original sender. Crediting a deposit account with a staked balance might be the wrong thing to do if that account doesn't have a key, for example.

**Comment by wjmelements** [comment]
We have yet to enable token fallbacks so this behavior can still change at this point without harming the ecosystem.

**Comment by vanruch** [comment]
Outdated issue
