### ISSUE TITLE
importing TokenFaucet.sol into Remix IDE

### ISSUE THREAD

**Issue by DGalinecEY** [trusttoken/true-currencies#126]
Hi,

I have error when importing TokenFaucet.sol into Remix IDE
import "github.com/trusttoken/true-currencies/contracts/utilities/TokenFaucet.sol";

It seems that some files cannot be found.

**Comment by wjmelements** [comment]
Did you pull the git submodules?

**Comment by DGalinec** [comment]
Hi,

Issue is solved. Thank you!
