### ISSUE TITLE
**CLA Signature Action:** All authors have signed the CLA. You may need to manually re-run the blocking PR check if it doesn't pass in a few minutes.

### ISSUE THREAD

**Issue by fredbuluku** [trusttoken/true-currencies#316]
**CLA Signature Action:** All authors have signed the CLA. You may need to manually re-run the blocking PR check if it doesn't pass in a few minutes.

__Originally posted by @github-actions in https://github.com/MetaMask/metamask-extension/pull/9549#issuecomment-706743421__

**Comment by vanruch** [comment]
Hi @fredbuluku 👋. Could you please elaborate on this issue?

**Comment by fredbuluku** [comment]
It was about security but I sorted out through settings,thank you for your concern.

**Comment by vanruch** [comment]
Good to hear!
