### ISSUE TITLE
Error: Could not find artifacts for MultisigOwner from any sources

### ISSUE THREAD

**Issue by umanggoyal89** [trusttoken/true-currencies#99]
Hi
I am trying to setup TrueUSD coin so i can test it with my exchange but i am not able to setup it. I am not an expert but i am facing this issue:
Error: Could not find artifacts for MultisigOwner from any sources
I cloned the repository and then followed the commands mentioned in the readme
1. git submodule init && git submodule update
2. npm install
3. npm test
While running npm test i am facing this issue.

Does any one knows what am i missing or not doing correct?

**Comment by wjmelements** [comment]
Sorry for the delay in response. You can get faster exchange support in the future by emailing `exchange-support` at `trusttoken.com`.

I do not experience this issue when I follow these steps. I'm going to ask a few questions to help diagnose the issue.

From our project directory, what is your output for `ls build/contracts`? Do you see `MultisigOwner.json`?

I'm pretty sure `npm test` runs `truffle compile`, but do you also see the issue if you explicitly compile first?

**Comment by wjmelements** [comment]
If you need to set it up on a testnet, it may be faster to use our deployments on Rinkeby, documented in our README.

**Comment by wjmelements** [comment]
We are now also on Kovan.

**Comment by wjmelements** [comment]
@umanggoyal89 I will close this issue if you do not respond shortly.

**Comment by vanruch** [comment]
@umanggoyal89 We have merged all contract repositories into one, so there's no reason for Multisig to be missing anymore
